### ISSUE TITLE
Only three classes predicted on multi-class training.

### ISSUE THREAD

**Issue by Kasatusss** [zhixinwang/frustum-convnet#32]
Hello! Thanks for your work!

I've faced a problem. I want to use F-ConvNet to predict 3d boxes for `['Car', 'Cyclist', 'Pedestrian', 'Truck', 'Van']` classes. 
For this I've changed: 
1. `datasets/dataset_info.py` according to these classes; 
2.  `kitti/prepare_data.py`, namely `type_whitelist = ['Car', 'Cyclist', 'Pedestrian', 'Truck', 'Van']`
3. `kitti/prepare_data_refine.py`, namely `type_whitelist = ['Car', 'Cyclist', 'Pedestrian', 'Truck', 'Van']`
4. `datasets/provider_sample.py`, namely `one_hot_vec = 5`.

So, I have `.pickle` files with all classes five I want. 
**However**, after training (via `train_net_det.py`) and testing (via `test_net_det.py`) the first stage and the second stage, I've got only `['Car', 'Cyclist', 'Pedestrian']` in **predictions**.

Can anyone help with this problem?

**Comment by zhixinwang** [comment]
You need to provide 2D detection results of other categories in `kitti/rgb_detections/rgb_detection_val.txt`. Now the categories are  {1: 'Pedestrian', 2: 'Car', 3: 'Cyclist'}.

**Comment by Kasatusss** [comment]
Oh, really :) I've missed it. Thanks!

Can you help me with other questions?
1. What are **CLASS_MEAN_SIZE**s in `dataset_info.py` use for? Where can I find these parameters for other classes?
2. In case I train this model on multi-classes, should I specify **STRIDE** and **HEIGHT_HALF** in config for each class separately? What's the use of these parameters and how do they affect metrics?

**Comment by zhixinwang** [comment]
1. You can calculate the mean object size of KITTI train set. Refer the `get_box3d_dim_statistics` function in `kitti/prepare_data.py`.
2. We construct multi-resolution frustums to fuse different scale feature in order to decrease the influence of  `STRIDE` and `HEIGHT_HALF`. The empirical suggestion is to make the detector head have a suitable receptive field.  I think it's also an opportunity to construct a selection mechanism like FPN variants in 2D image detection.
